name: vtadmin_web_ci
on: 
  pull_request:
    paths:
      - 'web/vtadmin/**'

defaults:
  run:
    working-directory: ./web/vtadmin

jobs:   
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Note from the docs: https://github.com/actions/cache/blob/main/examples.md#node---npm
    #
    #   It is not recommended to cache node_modules, as it can break across Node versions 
    #   and won't work with npm ci
    #
    - name: Install dependencies
      run: npm ci
    
    - name: Build front-end
      run: npm run build

    - name: Run unit tests
      run: npm run test
    
    - name: Run eslint
      run: npm run lint:eslint
    
    - name: Run prettier
      run: npm run lint:prettier
    
    - name: Run stylelint
      run: npm run lint:stylelint
