name: vtadmin_web_build
on: 
  pull_request:
    paths:
      - 'web/vtadmin/**'

defaults:
  run:
    working-directory: ./web/vtadmin

jobs:   
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # Reference: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
    - name: Cache node_modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build front-end
      run: npm run build
    
    - name: Run eslint
      run: npm run lint:eslint
    
    - name: Run prettier
      run: npm run lint:prettier
    
    - name: Run stylelint
      run: npm run lint:stylelint
